<%-- 
    Document   : AdmissionBookRegister_Fem
    Created on : May 13, 2011, 4:58:49 PM
    Author     : trainee
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<%@taglib prefix="s" uri="/struts-tags"%>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <script>
            function call_action()
            {
                document.adm_reg_fem.action = 'loadchdetails.action';
                document.adm_reg_fem.submit();
            }
        </script>
        <script type="text/javascript">
            <jsp:include page="../../javascripts/adm_med_regfem_javascript.jsp"></jsp:include> 
        </script>
    </head>
    <body onload="document.getElementById('dialog-form_adm_reg_fem').style.visibility='hidden'">

            <%--<s:property value="testing"/>--%>
            <%--<s:if test="%{testing == 'admismedregfirst'}">
                <center>
            <CAPTION><font size="3"><b>Medical Admission Register</b></font></CAPTION>
                <table border="1">
            <s:form name="adm_reg" action="storeadmbookregister" method="POST" theme="css_xhtml" id="adm_reg">
                <tr><td colspan="2" align="center"><s:select label="Profile Id & Name" name="adm_reg_profile_id" id="adm_reg_profile_id" labelposition="left" headerKey="1" headerValue="--Please Select--" list="child_profid_list" listKey="childProfileId" listValue="%{childName+'---->'+childProfileId}" onchange="call_action();"/></td></tr>
                <tr><td align="right">Date & Time of Admission:</td><td><s:textfield name="adm_reg_date_time" readonly="true"/></td></tr>
                <tr><td align="right">From Where:</td><td><s:textfield name="adm_reg_from_where" id="adm_reg_from_where" readonly="true"/></td></tr>
                <tr><td align="right">Age:</td><td><s:textfield name="adm_reg_age" readonly="true"/></td></tr>
                <tr><td align="right">Identification Marks:</td><td><s:textfield name="adm_reg_iden_marks" readonly="true"/></td></tr>
                <tr><td align="right">Weight at the time of admission(in kgs):</td><td><s:textfield name="adm_reg_adm_weight" id="adm_reg_adm_weight"/></td></tr>
                <tr><td align="right">Height at the time of admission(in cms):</td><td><s:textfield name="adm_reg_adm_height" id="adm_reg_adm_height"/></td></tr>
                <tr><td colspan="2" align="center"><b>Specific Complaints</b></td></tr>
                <tr><td align="right">Any Congenital Anomalies:</td><td><s:radio name="adm_reg_conano" id="adm_reg_conano" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('adm_reg_conano','ca');"/><div id='ca'><s:textfield label="Specify Name" name="adm_reg_conano_specify" labelposition="left" id="adm_reg_conano_specify"/></div></td></tr>
                <tr><td align="right">Physically Handicapped:</td><td><s:radio name="adm_reg_phyhan" id="adm_reg_phyhan" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('adm_reg_phyhan','ph');"/><div id='ph'><s:textfield label="Specify % of Disability" name="adm_reg_phyhan_specify" labelposition="left" id="adm_reg_phyhan_specify"/></div></td></tr>
                <tr><td align="right">Mentally Handicapped:</td><td><s:radio name="adm_reg_menhan" id="adm_reg_menhan" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('adm_reg_menhan','mh');"/><div id='mh'><s:select label="Specify Status" name="adm_reg_menhan_specify" headerKey="select" headerValue="-- Please Select --" list="#{'Mild':'Mild','Moderate':'Moderate','Severe':'Severe'}" labelposition="left" id="adm_reg_menhan_specify"/></div></td></tr>
                <tr><td align="right">Known Case of Fits:</td><td><s:radio name="adm_reg_fits_case" id="adm_reg_fits_case" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('adm_reg_fits_case','fc');"/><div id='fc'><s:textfield label="Specify Treatment" name="adm_reg_fitstreat_specify" labelposition="left" id="adm_reg_fitstreat_specify"/></div></td></tr>
                <tr><td align="right">History of any Communicable<br>Diseases:</td><td><s:radio name="adm_reg_commd_hist" id="adm_reg_commd_hist" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('adm_reg_commd_hist','cd');"/><div id='cd'><s:select label="Specify Disease" name="adm_reg_commd_specify" headerKey="select" headerValue="-- Please Select --" list="#{'TB':'TB','HIV':'HIV','Scabies':'Scabies','STD':'STD','Others':'Others'}" labelposition="left" id="adm_reg_commd_specify"/></div></td></tr>
                <tr><td align="right">Specify Others:</td><td><s:textfield name="adm_reg_commd_others" id="adm_reg_commd_others"/></td></tr>
                <tr><td colspan="2" align="center"><b>General Complaints</b></td></tr>
                <tr><td align="right">Body Pains:</td><td><s:radio name="adm_reg_body_pains" id="adm_reg_body_pains" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}"/></td></tr>
                <tr><td align="right">Fever:</td><td><s:radio name="adm_reg_fever" id="adm_reg_fever" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}"/></td></tr>
                <tr><td align="right">Vomiting:</td><td><s:radio name="adm_reg_vomiting" id="adm_reg_vomiting" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}"/></td></tr>
                <tr><td align="right">Others Specify:</td><td><s:textfield name="adm_reg_gencomp_others" id="adm_reg_gencomp_others"/></td></tr>
                <tr><td align="right">Previous Health History:</td><td><s:textfield name="adm_reg_prev_hist" id="adm_reg_prev_hist"/></td></tr>
                <tr><td colspan="2" align="center"><b>General Condition at the Time of Admission</b></td></tr>
                <tr><td align="right">Physical Appearance:</td><td><s:radio name="adm_reg_phyapp" id="adm_reg_phyapp" list="#{'normal':'Normal','sick':'Sick'}" value="%{'normal'}"/></td></tr>
                <tr><td align="right">Conscious Level<br>(History Of Drug Addiction):</td><td><s:radio name="adm_reg_drug_addiction" id="adm_reg_drug_addiction" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('adm_reg_drug_addiction','cl');"/><div id='cl'><s:textfield label="Specify Drug" name="adm_reg_drug_specify" id="adm_reg_drug_specify" labelposition="left"/></div></td></tr>
                <tr><td align="right">Anemic:</td><td><s:radio name="adm_reg_anemic" id="adm_reg_anemic" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('adm_reg_anemic','an');"/><div id='an'><s:select label="Level" name="adm_reg_anemic_level" id="adm_reg_anemic_level" headerKey="select" headerValue="-- Please Select --" list="#{'Mild':'Mild','Moderate':'Moderate','Severe':'Severe'}" labelposition="left"/></div></td></tr>
                <tr><td align="right">Heart:</td><td><table><tr><td align="right">CHD:</td><td><s:radio name="heartChd" id="adm_reg_heart_chd" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" labelposition="right"/></td></tr><tr><td align="right">Murmur:</td><td><s:radio id="adm_reg_heart_murmur" name="murmur" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" labelposition="right"/></td></tr><tr><td align="right">Heart Sounds:</td><td><s:radio name="heartSounds" id="adm_reg_heart_sounds" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" labelposition="right"/></td></tr></table></td></tr>
                <tr><td align="right">Lungs:</td><td><table><tr><td align="right">Any Chest Abnormalities:</td><td><s:radio name="chestAbnormal" id="adm_reg_chest_abnor" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" labelposition="left"/></td></tr><tr><td align="right">Crepts:</td><td><s:radio name="crepts" id="adm_reg_lungs_crepts" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" labelposition="left"/></td></tr><tr><td align="right">BAE:</td><td><s:radio name="lungsBea" id="adm_reg_lungs_bae" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" labelposition="left"/></td></tr></table></td></tr>
                <tr><td align="right">Per-abdomen<br>(Any organomegaly):</td><td><s:radio name="adm_reg_parabdomen" id="adm_reg_parabdomen" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('adm_reg_parabdomen','pb');"/><div id='pb'><s:select label="Specify" name="adm_reg_parabdomen_specify" id="adm_reg_parabdomen_specify" headerKey="select" headerValue="-- Please Select --" list="#{'spleenomegaly':'Spleenomegaly','heptomegaly':'Heptomegaly'}" labelposition="left"/></div></td></tr>
                <tr><td align="right">Skin Diseases:</td><td><s:textfield name="adm_reg_skin_diseases" id="adm_reg_skin_diseases"/></td></tr>
                <tr><td colspan="2" align="center"><b>Provisional Diagnosis</b></td></tr>
                <tr><td align="right">CNS:</td><td><s:textfield name="adm_reg_cns" id="adm_reg_cns"/></td></tr>
                <tr><td align="right">CVS:</td><td><s:textfield name="adm_reg_cvs" id="adm_reg_cvs"/></td></tr>
                <tr><td align="right">Lungs:</td><td><s:textfield name="adm_reg_lungs" id="adm_reg_lungs"/></td></tr>
                <tr><td align="right">GIT:</td><td><s:textfield name="adm_reg_git" id="adm_reg_git"/></td></tr>
                <tr><td align="right">Kidney:</td><td><s:textfield name="adm_reg_kidney" id="adm_reg_kidney"/></td></tr>
                <tr><td align="right">Skeletal System:</td><td><s:textfield name="adm_reg_ske_sys" id="adm_reg_ske_sys"/></td></tr>
                <tr><td align="right">Others Specify:</td><td><s:textfield name="adm_reg_prodia_others" id="adm_reg_prodia_others"/></td></tr>
                <tr><td align="right">Medical Officer's <br>Suggestion:</td><td><s:textarea name="treatment" id="adm_reg_doctors_sugg" cols="20" rows="4"/></td></tr>
                <tr><td colspan="2" align="center"><s:submit value="Save" align="center"/></td></tr>
            </s:form>
         </table>
            </center>
            </s:if>
--%>
<s:if test="%{testing == 'admismedregselect'}">
<%session.setAttribute("form_name","adm_reg");%>

<center>
            <CAPTION><font size="3"><b><s:text name="global.heading.admRegister"/></b></font></CAPTION>
            <table border="1">
            <s:form name="adm_reg_fem" action="storeadmbookregister" method="POST" theme="css_xhtml" id="adm_reg_fem">
                <tr><td colspan="2" align="center"><s:text name='package.label.rrProfIdName'/><s:select name="adm_reg_profile_id" id="adm_reg_profile_id" labelposition="left" headerKey="1" headerValue="--Please Select--" list="child_profid_list" listKey="childProfileId" listValue="%{childName+'---->'+childProfileId}" value="%{child_det.childProfileId}" onchange="call_action();"/><%--<s:textfield label="Profile Id" name="adm_reg_profile_id" id="adm_reg_profile_id" labelposition="left" value="%{profile_det.userId}"/>--%></td></tr>
                <tr><td align="right"><s:text name="package.label.admregDate"/>:</td><td><s:textfield name="adm_reg_date_time" value="%{child_det.dateTimeAdm}" readonly="true" disabled="true"/></td></tr>
                <%--<tr><td align="right">Time Of Admission:</td><td><s:textfield name="adm_reg_time" value="%{child_det.dateTimeAdm.getHours()}:%{child_det.dateTimeAdm.getMinutes()}:%{child_det.dateTimeAdm.getSeconds()}"/></td></tr>--%>
                <s:hidden name="adm_reg_gender" value="%{child_det.gender}"></s:hidden>
                <tr><td align="right"><s:text name="package.label.admregFromWhere"/>:</td><td><s:textfield name="adm_reg_from_where" id="adm_reg_from_where" value="%{child_det.admThrough}" readonly="true" disabled="true"/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregAge"/>:</td><td><s:textfield name="adm_reg_age" value="%{child_det.age}" readonly="true" disabled="true"/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregIdenMarks"/>:</td><td><s:textfield name="adm_reg_iden_marks" value="%{child_det.identificationMarks}" readonly="true" disabled="true"/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregWeiAtAdm"/>:</td><td><s:textfield name="wtAdm" id="adm_reg_adm_weight"/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregHeiAtAdm"/>:</td><td><s:textfield name="htAdm" id="adm_reg_adm_height"/></td></tr>
                <tr><td colspan="2" align="center"><b><s:text name="package.label.admregComplainSpec"/></b></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCongiAno"/>:</td><td><input type="radio" name="congenitalAnomalies" id="adm_reg_conano" value="Y" onclick="admr_dynamic('congenitalAnomalies','ca');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="congenitalAnomalies" id="adm_reg_conano" value="N" onclick="admr_dynamic('congenitalAnomalies','ca');"/><s:text name="package.rad.label.no"/><%--s:radio name="congenitalAnomalies" id="adm_reg_conano" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('congenitalAnomalies','ca');"/--%><div id='ca'><s:text name="package.label.admregNameSpec"/>:<s:textfield name="specCongenital" labelposition="left" id="adm_reg_conano_specify" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregPhyHandi"/>:</td><td><input type="radio" name="phyHandicap" id="adm_reg_phyhan" value="Y" onclick="admr_dynamic('phyHandicap','ph');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="phyHandicap" id="adm_reg_phyhan" value="N" onclick="admr_dynamic('phyHandicap','ph');"/><s:text name="package.rad.label.no"/><%--s:radio name="phyHandicap" id="adm_reg_phyhan" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('phyHandicap','ph');"/--%><div id='ph'><s:text name="package.label.admregDisabSpec"/>:<s:textfield name="specifyPhyHandPercent" labelposition="left" id="adm_reg_phyhan_specify" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregMenHandi"/>:</td><td><input type="radio" name="mentalHand" id="adm_reg_menhan" value="Y" onclick="admr_dynamic('mentalHand','mh');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="mentalHand" id="adm_reg_menhan" value="N" onclick="admr_dynamic('mentalHand','mh');"/><s:text name="package.rad.label.no"/><%--s:radio name="mentalHand" id="adm_reg_menhan" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('mentalHand','mh');"/--%><div id='mh'><s:text name="package.label.admregStatSpec"/>:<s:if test="%{#request.locale.language=='en'}"><s:select name="adm_reg_menhan_specify" headerKey="select" headerValue="-- Please Select --" list="#{'Mild':'Mild','Moderate':'Moderate','Severe':'Severe'}" labelposition="left" id="adm_reg_menhan_specify"/></s:if><s:elseif test="%{#request.locale.language=='hi'}"><select name="adm_reg_menhan_specify" id="adm_reg_menhan_specify">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="select">--&#2325;&#2371;&#2346;&#2351;&#2366; &#2330;&#2369;&#2344;&#2375;&#2306;--</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2361;&#2354;&#2381;&#2325;&#2366;">&#2361;&#2354;&#2381;&#2325;&#2366;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2350;&#2343;&#2381;&#2351;&#2350;">&#2350;&#2343;&#2381;&#2351;&#2350;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2327;&#2306;&#2349;&#2368;&#2352;">&#2327;&#2306;&#2349;&#2368;&#2352;</option></select></s:elseif>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <s:elseif test="%{#request.locale.language=='te'}"><select name="adm_reg_menhan_specify" id="adm_reg_menhan_specify">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="select">--&#3110;&#3119;&#3098;&#3143;&#3128;&#3135; &#3086;&#3074;&#3098;&#3137;&#3093;&#3147;&#3074;&#3105;&#3135;--</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3108;&#3093;&#3149;&#3093;&#3137;&#3125; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;">&#3108;&#3093;&#3149;&#3093;&#3137;&#3125; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3118;&#3134;&#3110;&#3135;&#3120;&#3135; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;">&#3118;&#3134;&#3110;&#3135;&#3120;&#3135; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3108;&#3136;&#3125;&#3149;&#3120; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;">&#3108;&#3136;&#3125;&#3149;&#3120; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;</option></select></s:elseif></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFits"/>:</td><td><input type="radio" name="caseOfFits" id="adm_reg_fits_case" value="Y" onclick="admr_dynamic('caseOfFits','fc');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="caseOfFits" id="adm_reg_fits_case" value="N" onclick="admr_dynamic('caseOfFits','fc');"/><s:text name="package.rad.label.no"/><%--s:radio name="caseOfFits" id="adm_reg_fits_case" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('caseOfFits','fc');"/--%><div id='fc'><s:text name="package.label.admregTreatSpec"/>:<s:textfield name="fitsTreatment" labelposition="left" id="adm_reg_fitstreat_specify" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCommuHist"/>:</td><td><input type="radio" name="histCommunicableDisease" id="adm_reg_commd_hist" value="Y" onclick="admr_dynamic('histCommunicableDisease','cd');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="histCommunicableDisease" id="adm_reg_commd_hist" value="N" onclick="admr_dynamic('histCommunicableDisease','cd');"/><s:text name="package.rad.label.no"/><%--s:radio name="histCommunicableDisease" id="adm_reg_commd_hist" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('histCommunicableDisease','cd');"/--%><div id='cd'><s:text name="package.label.admregDiseaSpec"/>:<s:if test="%{#request.locale.language=='en'}"><s:select name="adm_reg_commd_specify" headerKey="select" headerValue="-- Please Select --" list="#{'TB':'TB','HIV':'HIV','Scabies':'Scabies','STD':'STD','Others':'Others'}" labelposition="left" id="adm_reg_commd_specify"/></s:if><s:elseif test="%{#request.locale.language=='hi'}"><select name="adm_reg_commd_specify" id="adm_reg_commd_specify">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="select">--&#2325;&#2371;&#2346;&#2351;&#2366; &#2330;&#2369;&#2344;&#2375;&#2306;--</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2335;&#2368;&#2348;&#2368;">&#2335;&#2368;&#2348;&#2368;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2319;&#2330;&#2310;&#2311;&#2357;&#2368;">&#2319;&#2330;&#2310;&#2311;&#2357;&#2368;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2360;&#2381;&#2325;&#2376;&#2348;&#2368;&#2395;">&#2360;&#2381;&#2325;&#2376;&#2348;&#2368;&#2395;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2319;&#2360;&#2335;&#2368;&#2337;&#2368;">&#2319;&#2360;&#2335;&#2368;&#2337;&#2368;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2309;&#2344;&#2381;&#2351;">&#2309;&#2344;&#2381;&#2351;</option></select></s:elseif>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <s:elseif test="%{#request.locale.language=='te'}"><select name="adm_reg_commd_specify" id="adm_reg_commd_specify">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="select">--&#3110;&#3119;&#3098;&#3143;&#3128;&#3135; &#3086;&#3074;&#3098;&#3137;&#3093;&#3147;&#3074;&#3105;&#3135;--</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3093;&#3149;&#3127;&#3119;&#3125;&#3149;&#3119;&#3134;&#3111;&#3135;">&#3093;&#3149;&#3127;&#3119;&#3125;&#3149;&#3119;&#3134;&#3111;&#3135;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3129;&#3142;&#3098;&#3149; &#3088; &#3125;&#3135;">&#3129;&#3142;&#3098;&#3149; &#3088; &#3125;&#3135;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3095;&#3100;&#3149;&#3100;&#3135;">&#3095;&#3100;&#3149;&#3100;&#3135;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3086;&#3128;&#3149; &#3103;&#3135; &#3105;&#3135;">&#3086;&#3128;&#3149; &#3103;&#3135; &#3105;&#3135;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3079;&#3108;&#3120;&#3118;&#3137;&#3122;&#3137;">&#3079;&#3108;&#3120;&#3118;&#3137;&#3122;&#3137;</option></select></s:elseif></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregSpecOth"/>:</td><td><s:textfield name="otherCommDisease" id="adm_reg_commd_others" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></td></tr>
                <tr><td colspan="2" align="center"><b><s:text name="package.label.admregComplainGen"/></b></td></tr>
                <tr><td align="right"><s:text name="package.label.admregBodyPain"/>:</td><td><input type="radio" name="bodyPains" id="adm_reg_body_pains" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="bodyPains" id="adm_reg_body_pains" value="N"/><s:text name="package.rad.label.no"/><%--s:radio name="bodyPains" id="adm_reg_body_pains" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}"/--%></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFever"/>:</td><td><input type="radio" name="fever" id="adm_reg_fever" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="fever" id="adm_reg_fever" value="N"/><s:text name="package.rad.label.no"/><%--s:radio name="fever" id="adm_reg_fever" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}"/--%></td></tr>
                <tr><td align="right"><s:text name="package.label.admregVomit"/>:</td><td><input type="radio" name="vomiting" id="adm_reg_vomiting" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="vomiting" id="adm_reg_vomiting" value="N"/><s:text name="package.rad.label.no"/><%--s:radio name="vomiting" id="adm_reg_vomiting" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}"/--%></td></tr>
                <tr><td align="right"><s:text name="package.label.admregOthSpec"/>:</td><td><s:textfield name="otherCompl" id="adm_reg_gencomp_others" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregPrevHealHist"/>:</td><td><s:textfield name="prevHealthHist" id="adm_reg_prev_hist" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></td></tr>
                <tr><td colspan="2" align="center"><b><s:text name="package.label.admregFemGenDet"/></b></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemMarStat"/>:</td><td><input type="radio" name="maritalStatus" id="adm_reg_marital_status" value="<s:text name="package.rad.label.married"/>"/><s:text name="package.rad.label.married"/><input type="radio" name="maritalStatus" id="adm_reg_marital_status" value="<s:text name="package.rad.label.unmarried"/>" checked/><s:text name="package.rad.label.unmarried"/><%--s:radio name="maritalStatus" id="adm_reg_marital_status" list="#{'Married':'Married','Unmarried':'Unmarried'}" value="%{'Unmarried'}"/--%></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemMenarAttai"/>:</td><td><input type="radio" name="attainedMenarche" id="adm_reg_attai_menar" value="Y" onclick="admr_dynamic('attainedMenarche','am');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="attainedMenarche" id="adm_reg_attai_menar" value="N" onclick="admr_dynamic('attainedMenarche','am');"/><s:text name="package.rad.label.no"/><%--s:radio name="attainedMenarche" id="adm_reg_attai_menar" list="#{'Y':'Yes','N':'No'}" value="%{'N'}" onclick="admr_dynamic('attainedMenarche','am');"/--%><div id='am'><s:text name="package.label.admregFemAtAge"/>:<s:textfield name="ageMenache" labelposition="left" id="adm_reg_agemen"/><br><s:text name="package.label.admregFemLMP"/>:<s:textfield name="lmp_temp" labelposition="left" id="datepicker" readonly="true"/></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemAbuse"/>:</td><td><input type="radio" name="sexualAbuse" id="adm_reg_sexual_abuse" value="Y"/><s:text name="package.rad.label.yes"/><input type="radio" name="sexualAbuse" id="adm_reg_sexual_abuse" value="N" checked/><s:text name="package.rad.label.no"/><%--s:radio name="sexualAbuse" id="adm_reg_sexual_abuse" list="#{'Y':'Yes','N':'No'}" value="%{'N'}"/--%></td></tr>
                <tr><td align="right"><b><s:text name="package.label.admregFemOnExam"/>:</b><br><s:text name="package.label.admregFemExtFin"/>:</td><td><s:textarea name="externalFindings" id="adm_reg_extfindings" cols="20" rows="4" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></td></tr>
                <%--<tr><td align="right">Local Examination:</td><td><s:checkbox name="localexam" id="adm_reg_localexam" label="Local Warts" value="Local Warts" labelposition="right"/><s:checkbox name="localexam" id="adm_reg_localexam" label="Discharges" value="Discharges" labelposition="right"/><s:checkbox name="localexam" id="adm_reg_localexam" label="Wounds" value="Wounds" labelposition="right"/><s:checkbox name="localexam" id="adm_reg_localexam" label="Scars" value="Scars" labelposition="right"/><s:checkbox name="localexam" id="adm_reg_localexam" label="Ulcers" value="Ulcers" labelposition="right"/><s:checkbox name="localexam" id="adm_reg_localexam" label="Pustules" value="Pustules" labelposition="right"/></td></tr>--%>
                <tr><td align="right"><s:text name="package.label.admregFemLocExam"/>:</td><td align=""><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemLocWar'/>" id="adm_reg_localexam"/><s:text name='global.checkLabel.admregFemLocWar'/><br/><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemDisc'/>" id="adm_reg_localexam"/><s:text name='global.checkLabel.admregFemDisc'/><br/><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemWoun'/>" id="adm_reg_localexam"/><s:text name='global.checkLabel.admregFemWoun'/><br/><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemPust'/>" id="adm_reg_localexam"/><s:text name='global.checkLabel.admregFemPust'/><br/><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemUlce'/>" id="adm_reg_localexam"/><s:text name='global.checkLabel.admregFemUlce'/><br/><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemScar'/>" id="adm_reg_localexam"/><s:text name='global.checkLabel.admregFemScar'/><br/><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemNA'/>" id="adm_reg_localexam"/><s:text name='global.checkLabel.admregFemNA'/><%--s:checkboxlist name="localexam" id="adm_reg_localexam" list="#{'LocalWarts':'LocalWarts','Discharges':'Discharges','Wounds':'Wounds','Pustules':'Pustules','Ulcers':'Ulcers','Scars':'Scars'}" labelposition="left"/--%></td></tr>

                <tr><td colspan="2" align="center"><b><s:text name="package.label.admregCondAtAdm"/></b></td></tr>
                <tr><td align="right"><s:text name="package.label.admregPhyAppear"/>:</td><td><input type="radio" name="phyAppear" id="adm_reg_phyapp" value="<s:text name="package.rad.label.normal"/>" checked/><s:text name="package.rad.label.normal"/><input type="radio" name="phyAppear" id="adm_reg_phyapp" value="<s:text name="package.rad.label.sick"/>"/><s:text name="package.rad.label.sick"/><%--s:radio name="phyAppear" id="adm_reg_phyapp" list="#{'normal':'Normal','sick':'Sick'}" value="%{'normal'}"/--%></td></tr>
                <tr><td align="right"><s:text name="package.label.admregConscLevel"/>:</td><td><input type="radio" name="drugAddiction" id="adm_reg_drug_addiction" value="Y" onclick="admr_dynamic('drugAddiction','cl');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="drugAddiction" id="adm_reg_drug_addiction" value="N" onclick="admr_dynamic('drugAddiction','cl');"/><s:text name="package.rad.label.no"/><%--s:radio name="drugAddiction" id="adm_reg_drug_addiction" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('drugAddiction','cl');"/--%><div id='cl'><s:text name="package.label.admregDrugSpec"/>:<s:textfield name="specifyDrug" id="adm_reg_drug_specify" labelposition="left" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregAnemic"/>:</td><td><input type="radio" name="anemic" id="adm_reg_anemic" value="Y" onclick="admr_dynamic('anemic','an');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="anemic" id="adm_reg_anemic" value="N" onclick="admr_dynamic('anemic','an');"/><s:text name="package.rad.label.no"/><%--s:radio name="anemic" id="adm_reg_anemic" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('anemic','an');"/--%><div id='an'><s:text name="package.label.admregLevel"/>:<s:if test="%{#request.locale.language=='en'}"><s:select name="adm_reg_anemic_level" id="adm_reg_anemic_level" headerKey="select" headerValue="-- Please Select --" list="#{'Mild':'Mild','Moderate':'Moderate','Severe':'Severe'}" labelposition="left"/></s:if><s:elseif test="%{#request.locale.language=='hi'}"><select name="adm_reg_anemic_level" id="adm_reg_anemic_level">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="select">--&#2325;&#2371;&#2346;&#2351;&#2366; &#2330;&#2369;&#2344;&#2375;&#2306;--</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2361;&#2354;&#2381;&#2325;&#2366;">&#2361;&#2354;&#2381;&#2325;&#2366;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2350;&#2343;&#2381;&#2351;&#2350;">&#2350;&#2343;&#2381;&#2351;&#2350;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2327;&#2306;&#2349;&#2368;&#2352;">&#2327;&#2306;&#2349;&#2368;&#2352;</option></select></s:elseif>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <s:elseif test="%{#request.locale.language=='te'}"><select name="adm_reg_anemic_level" id="adm_reg_anemic_level">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="select">--&#3110;&#3119;&#3098;&#3143;&#3128;&#3135; &#3086;&#3074;&#3098;&#3137;&#3093;&#3147;&#3074;&#3105;&#3135;--</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3108;&#3093;&#3149;&#3093;&#3137;&#3125; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;">&#3108;&#3093;&#3149;&#3093;&#3137;&#3125; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3118;&#3134;&#3110;&#3135;&#3120;&#3135; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;">&#3118;&#3134;&#3110;&#3135;&#3120;&#3135; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3108;&#3136;&#3125;&#3149;&#3120; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;">&#3108;&#3136;&#3125;&#3149;&#3120; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;</option></select></s:elseif></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregHeart"/>:</td><td><table><tr><td align="right"><s:text name="package.label.admregCHD"/>:</td><td><input type="radio" name="heartChd" id="adm_reg_heart_chd" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="heartChd" id="adm_reg_heart_chd" value="N"/><s:text name="package.rad.label.no"/><%--s:radio name="heartChd" id="adm_reg_heart_chd" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" labelposition="right"/--%></td></tr><tr><td align="right"><s:text name="package.label.admregMurmur"/>:</td><td><input type="radio" name="murmur" id="adm_reg_heart_murmur" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="murmur" id="adm_reg_heart_murmur" value="N"/><s:text name="package.rad.label.no"/><%--s:radio id="adm_reg_heart_murmur" name="murmur" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" labelposition="right"/--%></td></tr><tr><td align="right"><s:text name="package.label.admregHeaSound"/>:</td><td><input type="radio" name="heartSounds" id="adm_reg_heart_sounds" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="heartSounds" id="adm_reg_heart_sounds" value="N"/><s:text name="package.rad.label.no"/><%--s:radio name="heartSounds" id="adm_reg_heart_sounds" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" labelposition="right"/--%></td></tr></table></td></tr>
                <tr><td align="right"><s:text name="package.label.admregHeadLungs"/>:</td><td><table><tr><td align="right"><s:text name="package.label.admregChestAbnor"/>:</td><td><input type="radio" name="chestAbnormal" id="adm_reg_chest_abnor" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="chestAbnormal" id="adm_reg_chest_abnor" value="N"/><s:text name="package.rad.label.no"/><%--s:radio name="chestAbnormal" id="adm_reg_chest_abnor" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" labelposition="left"/--%></td></tr><tr><td align="right"><s:text name="package.label.admregCerpts"/>:</td><td><input type="radio" name="crepts" id="adm_reg_lungs_crepts" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="crepts" id="adm_reg_lungs_crepts" value="N"/><s:text name="package.rad.label.no"/><%--s:radio name="crepts" id="adm_reg_lungs_crepts" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" labelposition="left"/--%></td></tr><tr><td align="right"><s:text name="package.label.admregBAE"/>:</td><td><input type="radio" name="lungsBea" id="adm_reg_lungs_bae" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="lungsBea" id="adm_reg_lungs_bae" value="N"/><s:text name="package.rad.label.no"/><%--s:radio name="lungsBea" id="adm_reg_lungs_bae" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" labelposition="left"/--%></td></tr></table></td></tr>
                <tr><td align="right"><s:text name="package.label.admregPerAbdomen"/>:</td><td><input type="radio" name="parabdomenOrg" id="adm_reg_parabdomen" value="Y" onclick="admr_dynamic('parabdomenOrg','pb');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="parabdomenOrg" id="adm_reg_parabdomen" value="N" onclick="admr_dynamic('parabdomenOrg','pb');"/><s:text name="package.rad.label.no"/><%--s:radio name="parabdomenOrg" id="adm_reg_parabdomen" list="#{'Y':'Yes','N':'No'}" value="%{'Y'}" onclick="admr_dynamic('parabdomenOrg','pb');"/--%><div id='pb'><s:text name="package.label.admregSpecify"/>:<s:if test="%{#request.locale.language=='en'}"><s:select name="adm_reg_parabdomen_specify" id="adm_reg_parabdomen_specify" headerKey="select" headerValue="-- Please Select --" list="#{'spleenomegaly':'Spleenomegaly','heptomegaly':'Heptomegaly'}" labelposition="left"/></s:if><s:elseif test="%{#request.locale.language=='hi'}"><select name="adm_reg_parabdomen_specify" id="adm_reg_parabdomen_specify">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="select">--&#2325;&#2371;&#2346;&#2351;&#2366; &#2330;&#2369;&#2344;&#2375;&#2306;--</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2360;&#2381;&#2346;&#2381;&#2354;&#2368;&#2344;&#2379;&#2350;&#2368;&#2327;&#2354;&#2368;">&#2360;&#2381;&#2346;&#2381;&#2354;&#2368;&#2344;&#2379;&#2350;&#2368;&#2327;&#2354;&#2368;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2361;&#2375;&#2346;&#2381;&#2335;&#2379;&#2350;&#2368;&#2327;&#2354;&#2368;">&#2361;&#2375;&#2346;&#2381;&#2335;&#2379;&#2350;&#2368;&#2327;&#2354;&#2368;</option></select></s:elseif>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <s:elseif test="%{#request.locale.language=='te'}"><select name="adm_reg_parabdomen_specify" id="adm_reg_parabdomen_specify">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="select">--&#3110;&#3119;&#3098;&#3143;&#3128;&#3135; &#3086;&#3074;&#3098;&#3137;&#3093;&#3147;&#3074;&#3105;&#3135;--</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3114;&#3149;&#3122;&#3136;&#3129;&#3074; &#3128;&#3134;&#3095;&#3137;&#3110;&#3122;">&#3114;&#3149;&#3122;&#3136;&#3129;&#3074; &#3128;&#3134;&#3095;&#3137;&#3110;&#3122;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3093;&#3134;&#3122;&#3143;&#3119;&#3074; &#3128;&#3134;&#3095;&#3137;&#3110;&#3122;">&#3093;&#3134;&#3122;&#3143;&#3119;&#3074; &#3128;&#3134;&#3095;&#3137;&#3110;&#3122;</option></select></s:elseif></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregSkinDisea"/>:</td><td><s:textfield name="skinDiseases" id="adm_reg_skin_diseases" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></td></tr>
                <tr><td colspan="2" align="center"><b><s:text name="package.label.admregProvDiag"/></b></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCNS"/>:</td><td><s:textfield name="cnsDiag" id="adm_reg_cns" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCVS"/>:</td><td><s:textfield name="cvsDiag" id="adm_reg_cvs" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregLabelLungs"/>:</td><td><s:textfield name="lungsDiag" id="adm_reg_lungs" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregGIT"/>:</td><td><s:textfield name="gitDiag" id="adm_reg_git" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregKidney"/>:</td><td><s:textfield name="kidneyDiag" id="adm_reg_kidney" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregSkeSys"/>:</td><td><s:textfield name="skeletalSysDiag" id="adm_reg_ske_sys" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregOthSpec"/>:</td><td><s:textfield name="otherDiag" id="adm_reg_prodia_others" maxLength="73" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregOffiSuggest"/>:</td><td><s:textarea name="treatment" id="adm_reg_doctors_sugg" cols="20" rows="4" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'/></td></tr>
                <tr><td colspan="2" align="center"><input type="submit" value="<s:text name="package.button.admregSave"/>" align="center"/></td></tr>
            </s:form>
         </table>
        </center>
        <div id="dialog-form_adm_reg_fem" title="<s:text name="global.heading.admRegister"/> <s:text name="global.heading.preview"/>">
	<form name="adm_reg_dialog">
	<table border="1">
                <tr><td align="right"><s:text name='package.label.rrProfId'/>:</td><td><span id="adm_reg_profile_id_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregWeiAtAdm"/>:</td><td><span id="adm_reg_adm_weight_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregHeiAtAdm"/>:</td><td><span id="adm_reg_adm_height_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCongiAno"/>:</td><td><span id="adm_reg_conano_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregNameSpec"/>:</td><td><span id="adm_reg_conano_specify_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregPhyHandi"/>:</td><td><span id="adm_reg_phyhan_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregDisabSpec"/></td><td><span id="adm_reg_phyhan_specify_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregMenHandi"/>:</td><td><span id="adm_reg_menhan_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregStatSpec"/>:</td><td><span id="adm_reg_menhan_specify_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFits"/>:</td><td><span id="adm_reg_fits_case_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregTreatSpec"/>:</td><td><span id="adm_reg_fitstreat_specify_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCommuHist"/>:</td><td><span id="adm_reg_commd_hist_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregDiseaSpec"/>:</td><td><span id="adm_reg_commd_specify_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregSpecOth"/>:</td><td><span id="adm_reg_commd_others_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregBodyPain"/>:</td><td><span id="adm_reg_body_pains_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFever"/>:</td><td><span id="adm_reg_fever_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregVomit"/>:</td><td><span id="adm_reg_vomiting_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregOthSpec"/>:</td><td><span id="adm_reg_gencomp_others_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregPrevHealHist"/>:</td><td><span id="adm_reg_prev_hist_span"></span></td></tr>
                <!--for Female gender-->
                <tr><td align="right"><s:text name="package.label.admregFemMarStat"/>:</td><td><span id="adm_reg_mar_stat_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemMenarAttai"/>:</td><td><span id="adm_reg_att_menar_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemAtAge"/>:</td><td><span id="adm_reg_memar_age_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemLMP"/>:</td><td><span id="adm_reg_lmp_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemAbuse"/>:</td><td><span id="adm_reg_seabuse_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemExtFin"/>:</td><td><span id="adm_reg_exter_fin_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemLocExam"/>:</td><td><span id="adm_reg_loc_fin_span"></span></td></tr>
                <!--for Female gender-->
                <tr><td align="right"><s:text name="package.label.admregPhyAppear"/>:</td><td><span id="adm_reg_phyapp_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregConscLevel"/>:</td><td><span id="adm_reg_drug_addiction_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregDrugSpec"/>:</td><td><span id="adm_reg_drug_specify_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregAnemic"/>:</td><td><span id="adm_reg_anemic_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregLevel"/>:</td><td><span id="adm_reg_anemic_level_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregHeart"/> <s:text name="package.label.admregCHD"/>:</td><td><span id="adm_reg_heart_chd_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregHeart"/> <s:text name="package.label.admregMurmur"/>:</td><td><span id="adm_reg_heart_murmur_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregHeaSound"/>:</td><td><span id="adm_reg_heart_sounds_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregChestAbnor"/>:</td><td><span id="adm_reg_chest_abnor_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCerpts"/>:</td><td><span id="adm_reg_lungs_crepts_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregBAE"/>:</td><td><span id="adm_reg_lungs_bae_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregPerAbdomen"/>:</td><td><span id="adm_reg_parabdomen_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregSpecify"/>:</td><td><span id="adm_reg_parabdomen_specify_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregSkinDisea"/>:</td><td><span id="adm_reg_skin_diseases_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCNS"/>:</td><td><span id="adm_reg_cns_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCVS"/>:</td><td><span id="adm_reg_cvs_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregLabelLungs"/>:</td><td><span id="adm_reg_lungs_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregGIT"/>:</td><td><span id="adm_reg_git_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregKidney"/>:</td><td><span id="adm_reg_kidney_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregSkeSys"/>:</td><td><span id="adm_reg_ske_sys_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregOthSpec"/>:</td><td><span id="adm_reg_prodia_others_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregOffiSuggest"/>:</td><td><span id="adm_reg_doctors_sugg_span"></span></td></tr>
        </table>
	</form>
        </div>


</s:if>
<s:else>
    <h2><s:text name="global.errmsg.DocMajErrConAdmin"/></h2>
</s:else>
    </body>
</html>
