<%-- 
    Document   : UpdateAdmissionBookReg_Fem
    Created on : May 26, 2011, 9:30:08 AM
    Author     : trainee
--%>
<%@page import="com.cdac.hospitalmodule.Actions.HospitalModuleAction"%>
<%@page import="com.cdac.usermanagement.ORM.AdmMedicalRegister"%>
<%@page import="java.util.ArrayList"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<%@taglib prefix="s" uri="/struts-tags"%>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <script>
            function call_action()
            {
                document.update_adm_reg_fem.action = 'loadmodifydetails.action';
                document.update_adm_reg_fem.submit();
            }
        </script>
        <script type="text/javascript">
            <jsp:include page="../../javascripts/upda_admregfem_javascript.jsp"></jsp:include> 
        </script>
    </head>
    <body onload="document.getElementById('dialog-form_update_adm_reg_fem').style.visibility='hidden'">
        <s:if test="%{testing == 'updateadmregselect'}">
<%session.setAttribute("form_name","adm_reg");%>
this is for female gender
<center>
    <% 
AdmMedicalRegister adm=null;

//HospitalModuleAction hst;
System.out.println(session.getAttribute("dataList")+"in jsp");
//System.out.println(hst.getRequest().getAttribute("dataList")+": jsp");
adm= session.getAttribute("dataList")!=null? (AdmMedicalRegister)session.getAttribute("dataList"): null;
String spec=null;
//for(AdmMedicalRegister adm : data){

 //spec=adm.getSpecifyParabdomen();   
//}
System.out.println(spec+": in jsp:spec");
%>
            <CAPTION><font size="3"><b><s:text name="global.heading.updateadmRegister"/></b></font></CAPTION>
            <table border="1">
            <s:form name="update_adm_reg_fem" action="updateadmbookregister" method="POST" theme="css_xhtml" id="update_adm_reg_fem">
                <tr><td colspan="2" align="center"><s:text name='package.label.rrProfIdName'/>:<s:select name="adm_reg_profile_id" id="upda_adm_reg_profile_id" labelposition="left" headerKey="1" headerValue="--Please Select--" list="child_profid_list" listKey="childProfileId" listValue="%{childName+'---->'+childProfileId}" value="%{child_det.childProfileId}" onchange="call_action();"/><%--<s:textfield label="Profile Id" name="adm_reg_profile_id" id="adm_reg_profile_id" labelposition="left" value="%{profile_det.userId}"/>--%></td></tr>
                <tr><td align="right"><s:text name="package.label.admregDate"/>:</td><td><s:textfield name="adm_reg_date_time" value="%{child_det.dateTimeAdm}" readonly="true" disabled="true"/></td></tr>
                <%--<tr><td align="right">Time Of Admission:</td><td><s:textfield name="adm_reg_time" value="%{child_det.dateTimeAdm.getHours()}:%{child_det.dateTimeAdm.getMinutes()}:%{child_det.dateTimeAdm.getSeconds()}"/></td></tr>--%>
                <s:hidden name="adm_reg_gender" value="%{child_det.gender}"></s:hidden>
                <tr><td align="right"><s:text name="package.label.admregFromWhere"/>:</td><td><s:textfield name="adm_reg_from_where" id="adm_reg_from_where" value="%{child_det.admThrough}" readonly="true" disabled="true"/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregAge"/>:</td><td><s:textfield name="adm_reg_age" value="%{child_det.age}" readonly="true" disabled="true"/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregIdenMarks"/>:</td><td><s:textfield name="adm_reg_iden_marks" value="%{child_det.identificationMarks}" readonly="true" disabled="true"/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregWeiAtAdm"/>:</td><td><s:textfield name="wtAdm" id="upda_adm_reg_adm_weight" value="%{admreg_view.wtAdm}"/></td></tr>
                <tr><td align="right"><s:text name="package.label.admregHeiAtAdm"/>:</td><td><s:textfield name="htAdm" id="upda_adm_reg_adm_height" value="%{admreg_view.htAdm}"/></td></tr>
                <tr><td colspan="2" align="center"><b><s:text name="package.label.admregComplainSpec"/></b></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCongiAno"/>:</td><td>
                        <s:if test="%{#session.dataList.getCongenitalAnomalies()=='Y'}"><input type="radio" name="congenitalAnomalies" id="upda_adm_reg_conano" value="Y" onclick="admr_dynamic('congenitalAnomalies','ca');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="congenitalAnomalies" id="upda_adm_reg_conano" value="N" onclick="admr_dynamic('congenitalAnomalies','ca');"/><s:text name="package.rad.label.no"/></s:if>
                        <s:else><input type="radio" name="congenitalAnomalies" id="upda_adm_reg_conano" value="Y" onclick="admr_dynamic('congenitalAnomalies','ca');"/><s:text name="package.rad.label.yes"/><input type="radio" name="congenitalAnomalies" id="upda_adm_reg_conano" value="N" onclick="admr_dynamic('congenitalAnomalies','ca');" checked/><s:text name="package.rad.label.no"/></s:else>
                        <%--s:radio name="congenitalAnomalies" id="upda_adm_reg_conano" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.congenitalAnomalies}" onclick="admr_dynamic('congenitalAnomalies','ca');"/--%><div id='ca'><s:text name="package.label.admregNameSpec"/>:<br/><%--s:textfield name="specCongenital" labelposition="left" id="upda_adm_reg_conano_specify" value="%{admreg_view.specCongenital}" cssClass="keyboardInput"/--%><input type="text" name="specCongenital" id="upda_adm_reg_conano_specify" value="<%=adm.getSpecCongenital()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregPhyHandi"/>:</td><td>
                        <s:if test="%{#session.dataList.getPhyHandicap()=='Y'}"><input type="radio" name="phyHandicap" id="upda_adm_reg_phyhan" value="Y" onclick="admr_dynamic('phyHandicap','ph');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="phyHandicap" id="upda_adm_reg_phyhan" value="N" onclick="admr_dynamic('phyHandicap','ph');"/><s:text name="package.rad.label.no"/></s:if>
                        <s:else><input type="radio" name="phyHandicap" id="upda_adm_reg_phyhan" value="Y" onclick="admr_dynamic('phyHandicap','ph');"/><s:text name="package.rad.label.yes"/><input type="radio" name="phyHandicap" id="upda_adm_reg_phyhan" value="N" onclick="admr_dynamic('phyHandicap','ph');" checked/><s:text name="package.rad.label.no"/></s:else>
                        <%--s:radio name="phyHandicap" id="upda_adm_reg_phyhan" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.phyHandicap}" onclick="admr_dynamic('phyHandicap','ph');"/--%><div id='ph'><s:text name="package.label.admregDisabSpec"/>:<%--s:textfield name="specifyPhyHandPercent" labelposition="left" id="upda_adm_reg_phyhan_specify" value="%{admreg_view.specifyPhyHandPercent}" cssClass="keyboardInput"/--%><input type="text" name="specifyPhyHandPercent" id="upda_adm_reg_phyhan_specify" value="<%=adm.getSpecifyPhyHandPercent()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregMenHandi"/>:</td><td>
                        <s:if test="%{#session.dataList.getMentalHand()=='Y'}"><input type="radio" name="mentalHand" id="upda_adm_reg_menhan" value="Y" onclick="admr_dynamic('mentalHand','mh');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="mentalHand" id="upda_adm_reg_menhan" value="N" onclick="admr_dynamic('mentalHand','mh');"/><s:text name="package.rad.label.no"/></s:if>
                        <s:else><input type="radio" name="mentalHand" id="upda_adm_reg_menhan" value="Y" onclick="admr_dynamic('mentalHand','mh');"/><s:text name="package.rad.label.yes"/><input type="radio" name="mentalHand" id="upda_adm_reg_menhan" value="N" onclick="admr_dynamic('mentalHand','mh');" checked/><s:text name="package.rad.label.no"/></s:else>
                        <%--s:radio name="mentalHand" id="upda_adm_reg_menhan" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.mentalHand}" onclick="admr_dynamic('mentalHand','mh');"/--%><div id='mh'><s:text name="package.label.admregStatSpec"/>:<%--s:select name="specifyMentalHand" headerKey="none" headerValue="-- Please Select --" list="#{'Mild':'Mild','Moderate':'Moderate','Severe':'Severe'}" labelposition="left" id="upda_adm_reg_menhan_specify" value="%{admreg_view.specifyMentalHand}"/--%><%--s:if test="%{#request.locale.language=='en'}"><s:select name="specifyMentalHand" headerKey="select" headerValue="-- Please Select --" list="#{'Mild':'Mild','Moderate':'Moderate','Severe':'Severe'}" labelposition="left" id="upda_adm_reg_menhan_specify"/></s:if><s:elseif test="%{#request.locale.language=='hi'}"><select name="specifyMentalHand" id="upda_adm_reg_menhan_specify">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="select">--&#2325;&#2371;&#2346;&#2351;&#2366; &#2330;&#2369;&#2344;&#2375;&#2306;--</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2361;&#2354;&#2381;&#2325;&#2366;">&#2361;&#2354;&#2381;&#2325;&#2366;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2350;&#2343;&#2381;&#2351;&#2350;">&#2350;&#2343;&#2381;&#2351;&#2350;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2327;&#2306;&#2349;&#2368;&#2352;">&#2327;&#2306;&#2349;&#2368;&#2352;</option></select></s:elseif>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <s:elseif test="%{#request.locale.language=='te'}"><select name="specifyMentalHand" id="upda_adm_reg_menhan_specify">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="select">--&#3110;&#3119;&#3098;&#3143;&#3128;&#3135; &#3086;&#3074;&#3098;&#3137;&#3093;&#3147;&#3074;&#3105;&#3135;--</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3108;&#3093;&#3149;&#3093;&#3137;&#3125; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;">&#3108;&#3093;&#3149;&#3093;&#3137;&#3125; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3118;&#3134;&#3110;&#3135;&#3120;&#3135; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;">&#3118;&#3134;&#3110;&#3135;&#3120;&#3135; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3108;&#3136;&#3125;&#3149;&#3120; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;">&#3108;&#3136;&#3125;&#3149;&#3120; &#3128;&#3149;&#3109;&#3134;&#3119;&#3135;</option></select></s:elseif--%>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <select name="specifyMentalHand" id="upda_adm_reg_menhan_specify">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <s:if test="%{#session.dataList.getSpecifyMentalHand()=='none'}"><option value="none" selected>--<s:text name='global.selectOption.admregPleaSel'/>--</option></s:if>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <s:else><option value="none">--<s:text name='global.selectOption.admregPleaSel'/>--</option></s:else>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <s:if test="%{#session.dataList.getSpecifyMentalHand()==getText('global.selectOption.admregMHMild')}"><option value="<s:text name='global.selectOption.admregMHMild'/>" selected><s:text name="global.selectOption.admregMHMild"/></option></s:if>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <s:else><option value="<s:text name='global.selectOption.admregMHMild'/>"><s:text name="global.selectOption.admregMHMild"/></option></s:else>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <s:if test="%{#session.dataList.getSpecifyMentalHand()==getText('global.selectOption.admregMHMode')}"><option value="<s:text name='global.selectOption.admregMHMode'/>" selected><s:text name="global.selectOption.admregMHMode"/></option></s:if>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <s:else><option value="<s:text name='global.selectOption.admregMHMode'/>"><s:text name="global.selectOption.admregMHMode"/></option></s:else>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <s:if test="%{#session.dataList.getSpecifyMentalHand()==getText('global.selectOption.admregMHSeve')}"><option value="<s:text name='global.selectOption.admregMHSeve'/>" selected><s:text name="global.selectOption.admregMHSeve"/></option></s:if>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <s:else><option value="<s:text name='global.selectOption.admregMHSeve'/>"><s:text name="global.selectOption.admregMHSeve"/></option></s:else>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </select></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFits"/>:</td><td>
                        <s:if test="%{#session.dataList.getCaseOfFits()=='Y'}"><input type="radio" name="caseOfFits" id="upda_adm_reg_fits_case" value="Y" onclick="admr_dynamic('caseOfFits','fc');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="caseOfFits" id="upda_adm_reg_fits_case" value="N" onclick="admr_dynamic('caseOfFits','fc');"/><s:text name="package.rad.label.no"/></s:if>
                        <s:else><input type="radio" name="caseOfFits" id="upda_adm_reg_fits_case" value="Y" onclick="admr_dynamic('caseOfFits','fc');"/><s:text name="package.rad.label.yes"/><input type="radio" name="caseOfFits" id="upda_adm_reg_fits_case" value="N" onclick="admr_dynamic('caseOfFits','fc');" checked/><s:text name="package.rad.label.no"/></s:else>
                        <%--s:radio name="caseOfFits" id="upda_adm_reg_fits_case" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.caseOfFits}" onclick="admr_dynamic('caseOfFits','fc');"/--%><div id='fc'><s:text name="package.label.admregTreatSpec"/>:<%--s:textfield name="fitsTreatment" labelposition="left" id="upda_adm_reg_fitstreat_specify" value="%{admreg_view.fitsTreatment}" cssClass="keyboardInput"/--%><input type="text" name="fitsTreatment" id="upda_adm_reg_fitstreat_specify" value="<%=adm.getFitsTreatment()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCommuHist"/>:</td><td>
                        <s:if test="%{#session.dataList.getHistCommunicableDisease()=='Y'}"><input type="radio" name="histCommunicableDisease" id="upda_adm_reg_commd_hist" value="Y" onclick="admr_dynamic('histCommunicableDisease','cd');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="histCommunicableDisease" id="upda_adm_reg_commd_hist" value="N" onclick="admr_dynamic('histCommunicableDisease','cd');"/><s:text name="package.rad.label.no"/></s:if>
                        <s:else><input type="radio" name="histCommunicableDisease" id="upda_adm_reg_commd_hist" value="Y" onclick="admr_dynamic('histCommunicableDisease','cd');"/><s:text name="package.rad.label.yes"/><input type="radio" name="histCommunicableDisease" id="upda_adm_reg_commd_hist" value="N" onclick="admr_dynamic('histCommunicableDisease','cd');" checked/><s:text name="package.rad.label.no"/></s:else>
                        <%--s:radio name="histCommunicableDisease" id="upda_adm_reg_commd_hist" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.histCommunicableDisease}" onclick="admr_dynamic('histCommunicableDisease','cd');"/--%><div id='cd'><s:text name="package.label.admregDiseaSpec"/>:<%--s:select name="specifyCommDisease" headerKey="none" headerValue="-- Please Select --" list="#{'TB':'TB','HIV':'HIV','Scabies':'Scabies','STD':'STD','Others':'Others'}" labelposition="left" id="upda_adm_reg_commd_specify" value="%{admreg_view.specifyCommDisease}"/--%><%--s:if test="%{#request.locale.language=='en'}"><s:select name="specifyCommDisease" headerKey="select" headerValue="-- Please Select --" list="#{'TB':'TB','HIV':'HIV','Scabies':'Scabies','STD':'STD','Others':'Others'}" labelposition="left" id="upda_adm_reg_commd_specify"/></s:if><s:elseif test="%{#request.locale.language=='hi'}"><select name="specifyCommDisease" id="upda_adm_reg_commd_specify">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="select">--&#2325;&#2371;&#2346;&#2351;&#2366; &#2330;&#2369;&#2344;&#2375;&#2306;--</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2335;&#2368;&#2348;&#2368;">&#2335;&#2368;&#2348;&#2368;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2319;&#2330;&#2310;&#2311;&#2357;&#2368;">&#2319;&#2330;&#2310;&#2311;&#2357;&#2368;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2360;&#2381;&#2325;&#2376;&#2348;&#2368;&#2395;">&#2360;&#2381;&#2325;&#2376;&#2348;&#2368;&#2395;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2319;&#2360;&#2335;&#2368;&#2337;&#2368;">&#2319;&#2360;&#2335;&#2368;&#2337;&#2368;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#2309;&#2344;&#2381;&#2351;">&#2309;&#2344;&#2381;&#2351;</option></select></s:elseif>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <s:elseif test="%{#request.locale.language=='te'}"><select name="specifyCommDisease" id="upda_adm_reg_commd_specify">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="select">--&#3110;&#3119;&#3098;&#3143;&#3128;&#3135; &#3086;&#3074;&#3098;&#3137;&#3093;&#3147;&#3074;&#3105;&#3135;--</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3093;&#3149;&#3127;&#3119;&#3125;&#3149;&#3119;&#3134;&#3111;&#3135;">&#3093;&#3149;&#3127;&#3119;&#3125;&#3149;&#3119;&#3134;&#3111;&#3135;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3129;&#3142;&#3098;&#3149; &#3088; &#3125;&#3135;">&#3129;&#3142;&#3098;&#3149; &#3088; &#3125;&#3135;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3095;&#3100;&#3149;&#3100;&#3135;">&#3095;&#3100;&#3149;&#3100;&#3135;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3086;&#3128;&#3149; &#3103;&#3135; &#3105;&#3135;">&#3086;&#3128;&#3149; &#3103;&#3135; &#3105;&#3135;</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="&#3079;&#3108;&#3120;&#3118;&#3137;&#3122;&#3137;">&#3079;&#3108;&#3120;&#3118;&#3137;&#3122;&#3137;</option></select></s:elseif--%>
                            <select name="specifyCommDisease" id="upda_adm_reg_commd_specify">
                                <s:if test="%{#session.dataList.getSpecifyCommDisease()=='none'}"><option value="none" selected>--<s:text name='global.selectOption.admregPleaSel'/>--</option></s:if>
                                <s:else><option value="none">--<s:text name='global.selectOption.admregPleaSel'/>--</option></s:else>
                                <s:if test="%{#session.dataList.getSpecifyCommDisease()==getText('global.selectOption.admregCDTB')}"><option value="<s:text name='global.selectOption.admregCDTB'/>" selected><s:text name="global.selectOption.admregCDTB"/></option></s:if>
                                <s:else><option value="<s:text name='global.selectOption.admregCDTB'/>"><s:text name="global.selectOption.admregCDTB"/></option></s:else>
                                <s:if test="%{#session.dataList.getSpecifyCommDisease()==getText('global.selectOption.admregCDHIV')}"><option value="<s:text name='global.selectOption.admregCDHIV'/>" selected><s:text name="global.selectOption.admregCDHIV"/></option></s:if>
                                <s:else><option value="<s:text name='global.selectOption.admregCDHIV'/>"><s:text name="global.selectOption.admregCDHIV"/></option></s:else>
                                <s:if test="%{#session.dataList.getSpecifyCommDisease()==getText('global.selectOption.admregCDSca')}"><option value="<s:text name='global.selectOption.admregCDSca'/>" selected><s:text name="global.selectOption.admregCDSca"/></option></s:if>
                                <s:else><option value="<s:text name='global.selectOption.admregCDSca'/>"><s:text name="global.selectOption.admregCDSca"/></option></s:else>
                                <s:if test="%{#session.dataList.getSpecifyCommDisease()==getText('global.selectOption.admregCDSTD')}"><option value="<s:text name='global.selectOption.admregCDSTD'/>" selected><s:text name="global.selectOption.admregCDSTD"/></option></s:if>
                                <s:else><option value="<s:text name='global.selectOption.admregCDSTD'/>"><s:text name="global.selectOption.admregCDSTD"/></option></s:else>
                                <s:if test="%{#session.dataList.getSpecifyCommDisease()==getText('global.selectOption.admregCDOth')}"><option value="<s:text name='global.selectOption.admregCDOth'/>" selected><s:text name="global.selectOption.admregCDOth"/></option></s:if>
                                <s:else><option value="<s:text name='global.selectOption.admregCDOth'/>"><s:text name="global.selectOption.admregCDOth"/></option></s:else>
                            </select></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregSpecOth"/>:</td><td><%--s:textfield name="otherCommDisease" id="upda_adm_reg_commd_others" value="%{admreg_view.otherCommDisease}" cssClass="keyboardInput"/--%><input type="text" name="otherCommDisease" id="upda_adm_reg_commd_others" value="<%=adm.getOtherCommDisease()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></td></tr>
                <tr><td colspan="2" align="center"><b><s:text name="package.label.admregComplainGen"/></b></td></tr>
                <tr><td align="right"><s:text name="package.label.admregBodyPain"/>:</td><td>
                        <s:if test="%{#session.dataList.getBodyPains()=='Y'}"><input type="radio" name="bodyPains" id="upda_adm_reg_body_pains" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="bodyPains" id="upda_adm_reg_body_pains" value="N"/><s:text name="package.rad.label.no"/></s:if>
                        <s:else><input type="radio" name="bodyPains" id="upda_adm_reg_body_pains" value="Y"/><s:text name="package.rad.label.yes"/><input type="radio" name="bodyPains" id="upda_adm_reg_body_pains" value="N" checked/><s:text name="package.rad.label.no"/></s:else>
                        <%--s:radio name="bodyPains" id="upda_adm_reg_body_pains" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.bodyPains}"/--%></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFever"/>:</td><td>
                        <s:if test="%{#session.dataList.getFever()=='Y'}"><input type="radio" name="fever" id="upda_adm_reg_fever" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="fever" id="upda_adm_reg_fever" value="N"/><s:text name="package.rad.label.no"/></s:if>
                        <s:else><input type="radio" name="fever" id="upda_adm_reg_fever" value="Y"/><s:text name="package.rad.label.yes"/><input type="radio" name="fever" id="upda_adm_reg_fever" value="N" checked/><s:text name="package.rad.label.no"/></s:else>
                        <%--s:radio name="fever" id="upda_adm_reg_fever" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.fever}"/--%></td></tr>
                <tr><td align="right"><s:text name="package.label.admregVomit"/>:</td><td>
                        <s:if test="%{#session.dataList.getVomiting()=='Y'}"><input type="radio" name="vomiting" id="upda_adm_reg_vomiting" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="vomiting" id="upda_adm_reg_vomiting" value="N"/><s:text name="package.rad.label.no"/></s:if>
                        <s:else><input type="radio" name="vomiting" id="upda_adm_reg_vomiting" value="Y"/><s:text name="package.rad.label.yes"/><input type="radio" name="vomiting" id="upda_adm_reg_vomiting" value="N" checked/><s:text name="package.rad.label.no"/></s:else>
                        <%--s:radio name="vomiting" id="upda_adm_reg_vomiting" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.vomiting}"/--%></td></tr>
                <tr><td align="right"><s:text name="package.label.admregOthSpec"/>:</td><td><%--s:textfield name="otherCompl" id="upda_adm_reg_gencomp_others" value="%{admreg_view.otherCompl}" cssClass="keyboardInput"/--%><input type="text" name="otherCompl" id="upda_adm_reg_gencomp_others" value="<%=adm.getOtherCompl()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></td></tr>
                <tr><td align="right"><s:text name="package.label.admregPrevHealHist"/>:</td><td><%--s:textfield name="prevHealthHist" id="upda_adm_reg_prev_hist" value="%{admreg_view.prevHealthHist}" cssClass="keyboardInput"/--%><input type="text" name="prevHealthHist" id="upda_adm_reg_prev_hist" value="<%=adm.getPrevHealthHist()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></td></tr>

                <tr><td colspan="2" align="center"><b><s:text name="package.label.admregFemGenDet"/></b></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemMarStat"/>:</td><td>
                        <s:if test="%{#session.dataList.getMaritalStatus()==getText('package.rad.label.married')}"><input type="radio" name="maritalStatus" id="upda_adm_reg_marital_status" value="<s:text name="package.rad.label.married"/>" checked/><s:text name="package.rad.label.married"/><input type="radio" name="maritalStatus" id="upda_adm_reg_marital_status" value="<s:text name="package.rad.label.unmarried"/>"/><s:text name="package.rad.label.unmarried"/></s:if>
                        <s:else><input type="radio" name="maritalStatus" id="upda_adm_reg_marital_status" value="<s:text name="package.rad.label.married"/>"/><s:text name="package.rad.label.married"/><input type="radio" name="maritalStatus" id="upda_adm_reg_marital_status" value="<s:text name="package.rad.label.unmarried"/>" checked/><s:text name="package.rad.label.unmarried"/></s:else>
                        <%--s:radio name="maritalStatus" id="upda_adm_reg_marital_status" list="#{'Married':'Married','Unmarried':'Unmarried'}" value="%{admreg_view.maritalStatus}"/--%></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemMenarAttai"/>:</td><td>
                        <s:if test="%{#session.dataList.getAttainedMenarche()=='Y'}"><input type="radio" name="attainedMenarche" id="upda_adm_reg_attai_menar" value="Y" onclick="admr_dynamic('attainedMenarche','am');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="attainedMenarche" id="upda_adm_reg_attai_menar" value="N" onclick="admr_dynamic('attainedMenarche','am');"/><s:text name="package.rad.label.no"/></s:if>
                        <s:else><input type="radio" name="attainedMenarche" id="upda_adm_reg_attai_menar" value="Y" onclick="admr_dynamic('attainedMenarche','am');"/><s:text name="package.rad.label.yes"/><input type="radio" name="attainedMenarche" id="upda_adm_reg_attai_menar" value="N" onclick="admr_dynamic('attainedMenarche','am');" checked/><s:text name="package.rad.label.no"/></s:else>
                        <%--s:radio name="attainedMenarche" id="upda_adm_reg_attai_menar" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.attainedMenarche}" onclick="admr_dynamic('attainedMenarche','am');"/--%><div id='am'><s:text name="package.label.admregFemAtAge"/>:<s:textfield name="ageMenache" labelposition="left" id="upda_adm_reg_agemen" value="%{admreg_view.ageMenache}"/><br><s:text name="package.label.admregFemLMP"/>:<s:textfield name="lmp_temp" labelposition="left" id="datepicker" readonly="true" value="%{admreg_view.lmp}"/></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemAbuse"/>:</td><td>
                        <s:if test="%{#session.dataList.getSexualAbuse()=='Y'}"><input type="radio" name="sexualAbuse" id="upda_adm_reg_sexual_abuse" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="sexualAbuse" id="upda_adm_reg_sexual_abuse" value="N"/><s:text name="package.rad.label.no"/></s:if>
                        <s:else><input type="radio" name="sexualAbuse" id="upda_adm_reg_sexual_abuse" value="Y"/><s:text name="package.rad.label.yes"/><input type="radio" name="sexualAbuse" id="upda_adm_reg_sexual_abuse" value="N" checked/><s:text name="package.rad.label.no"/></s:else>
                        <%--s:radio name="sexualAbuse" id="upda_adm_reg_sexual_abuse" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.sexualAbuse}"/--%></td></tr>
                <tr><td align="right"><b><s:text name="package.label.admregFemOnExam"/>:</b><br><s:text name="package.label.admregFemExtFin"/>:</td><td><%--s:textarea name="externalFindings" id="upda_adm_reg_extfindings" cols="20" rows="4" value="%{admreg_view.externalFindings}" cssClass="keyboardInput"/--%><textarea name="externalFindings" id="upda_adm_reg_extfindings" cols="20" rows="4" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'><%=adm.getExternalFindings()%></textarea></td></tr>
                <%--<tr><td align="right">Local Examination:</td><td><s:checkbox name="localexam" id="adm_reg_localexam" label="Local Warts" value="Local Warts" labelposition="right"/><s:checkbox name="localexam" id="adm_reg_localexam" label="Discharges" value="Discharges" labelposition="right"/><s:checkbox name="localexam" id="adm_reg_localexam" label="Wounds" value="Wounds" labelposition="right"/><s:checkbox name="localexam" id="adm_reg_localexam" label="Scars" value="Scars" labelposition="right"/><s:checkbox name="localexam" id="adm_reg_localexam" label="Ulcers" value="Ulcers" labelposition="right"/><s:checkbox name="localexam" id="adm_reg_localexam" label="Pustules" value="Pustules" labelposition="right"/></td></tr>--%>
                <tr><td align="right"><s:text name="package.label.admregFemLocExam"/>:</td><td align="">
                                    <s:if test="%{admreg_locexamval.contains(getText('global.checkLabel.admregFemLocWar'))}"><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemLocWar'/>" id="upda_adm_reg_localexam" checked/><s:text name='global.checkLabel.admregFemLocWar'/><br/></s:if>
                                    <s:else><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemLocWar'/>" id="upda_adm_reg_localexam"/><s:text name='global.checkLabel.admregFemLocWar'/><br/></s:else>
                                    <s:if test="%{admreg_locexamval.contains(getText('global.checkLabel.admregFemDisc'))}"><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemDisc'/>" id="upda_adm_reg_localexam" checked/><s:text name='global.checkLabel.admregFemDisc'/><br/></s:if>
                                    <s:else><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemDisc'/>" id="upda_adm_reg_localexam"/><s:text name='global.checkLabel.admregFemDisc'/><br/></s:else>
                                    <s:if test="%{admreg_locexamval.contains(getText('global.checkLabel.admregFemWoun'))}"><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemWoun'/>" id="upda_adm_reg_localexam" checked/><s:text name='global.checkLabel.admregFemWoun'/><br/></s:if>
                                    <s:else><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemWoun'/>" id="upda_adm_reg_localexam"/><s:text name='global.checkLabel.admregFemWoun'/><br/></s:else>
                                    <s:if test="%{admreg_locexamval.contains(getText('global.checkLabel.admregFemPust'))}"><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemPust'/>" id="upda_adm_reg_localexam" checked/><s:text name='global.checkLabel.admregFemPust'/><br/></s:if>
                                    <s:else><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemPust'/>" id="upda_adm_reg_localexam"/><s:text name='global.checkLabel.admregFemPust'/><br/></s:else>
                                    <s:if test="%{admreg_locexamval.contains(getText('global.checkLabel.admregFemUlce'))}"><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemUlce'/>" id="upda_adm_reg_localexam" checked/><s:text name='global.checkLabel.admregFemUlce'/><br/></s:if>
                                    <s:else><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemUlce'/>" id="upda_adm_reg_localexam"/><s:text name='global.checkLabel.admregFemUlce'/><br/></s:else>
                                    <s:if test="%{admreg_locexamval.contains(getText('global.checkLabel.admregFemScar'))}"><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemScar'/>" id="upda_adm_reg_localexam" checked/><s:text name='global.checkLabel.admregFemScar'/><br/></s:if>
                                    <s:else><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemScar'/>" id="upda_adm_reg_localexam"/><s:text name='global.checkLabel.admregFemScar'/><br/></s:else>
                                    <s:if test="%{admreg_locexamval.contains(getText('global.checkLabel.admregFemNA'))}"><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemNA'/>" id="upda_adm_reg_localexam" checked/><s:text name='global.checkLabel.admregFemNA'/></s:if>
                                    <s:else><input type="checkbox" name="localexam" value="<s:text name='global.checkLabel.admregFemNA'/>" id="upda_adm_reg_localexam"/><s:text name='global.checkLabel.admregFemNA'/></s:else>
                                    <%--s:checkboxlist name="localexam" id="upda_adm_reg_localexam" list="#{'LocalWarts':'LocalWarts','Discharges':'Discharges','Wounds':'Wounds','Pustules':'Pustules','Ulcers':'Ulcers','Scars':'Scars'}" value="%{admreg_locexamval}" labelposition="left"/--%></td></tr>

                <tr><td colspan="2" align="center"><b><s:text name="package.label.admregCondAtAdm"/></b></td></tr>
                <tr><td align="right"><s:text name="package.label.admregPhyAppear"/>:</td><td>
                        
                        <s:if test="%{#session.dataList.getPhyAppear()==getText('package.rad.label.normal')}"><input type="radio" name="phyAppear" id="upda_adm_reg_phyapp" value="<s:text name="package.rad.label.normal"/>" checked/><s:text name="package.rad.label.normal"/><input type="radio" name="phyAppear" id="upda_adm_reg_phyapp" value="<s:text name="package.rad.label.sick"/>"/><s:text name="package.rad.label.sick"/></s:if>
                        <s:else><input type="radio" name="phyAppear" id="upda_adm_reg_phyapp" value="<s:text name="package.rad.label.normal"/>"/><s:text name="package.rad.label.normal"/><input type="radio" name="phyAppear" id="upda_adm_reg_phyapp" value="<s:text name="package.rad.label.sick"/>" checked/><s:text name="package.rad.label.sick"/></s:else>
                        <%--s:radio name="phyAppear" id="upda_adm_reg_phyapp" list="#{'normal':'Normal','sick':'Sick'}" value="%{admreg_view.phyAppear}"/--%></td></tr>
                <tr><td align="right"><s:text name="package.label.admregConscLevel"/>:</td><td>
                        <s:if test="%{#session.dataList.getDrugAddiction()=='Y'}"><input type="radio" name="drugAddiction" id="upda_adm_reg_drug_addiction" value="Y" onclick="admr_dynamic('drugAddiction','cl');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="drugAddiction" id="upda_adm_reg_drug_addiction" value="N" onclick="admr_dynamic('drugAddiction','cl');"/><s:text name="package.rad.label.no"/></s:if>
                        <s:else><input type="radio" name="drugAddiction" id="upda_adm_reg_drug_addiction" value="Y" onclick="admr_dynamic('drugAddiction','cl');"/><s:text name="package.rad.label.yes"/><input type="radio" name="drugAddiction" id="upda_adm_reg_drug_addiction" value="N" onclick="admr_dynamic('drugAddiction','cl');" checked/><s:text name="package.rad.label.no"/></s:else>
                        <%--s:radio name="drugAddiction" id="upda_adm_reg_drug_addiction" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.drugAddiction}" onclick="admr_dynamic('drugAddiction','cl');"/--%><div id='cl'><s:text name="package.label.admregDrugSpec"/>:<%--s:textfield name="specifyDrug" id="upda_adm_reg_drug_specify" labelposition="left" value="%{admreg_view.specifyDrug}" cssClass="keyboardInput"/--%><input type="text" name="specifyDrug" id="upda_adm_reg_drug_specify" value="<%=adm.getSpecifyDrug()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregAnemic"/>:</td><td>
                        <s:if test="%{#session.dataList.getAnemic()=='Y'}"><input type="radio" name="anemic" id="upda_adm_reg_anemic" value="Y" onclick="admr_dynamic('anemic','an');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="anemic" id="upda_adm_reg_anemic" value="N" onclick="admr_dynamic('anemic','an');"/><s:text name="package.rad.label.no"/></s:if>
                        <s:else><input type="radio" name="anemic" id="upda_adm_reg_anemic" value="Y" onclick="admr_dynamic('anemic','an');"/><s:text name="package.rad.label.yes"/><input type="radio" name="anemic" id="upda_adm_reg_anemic" value="N" onclick="admr_dynamic('anemic','an');" checked/><s:text name="package.rad.label.no"/></s:else>
                        <%--s:radio name="anemic" id="upda_adm_reg_anemic" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.anemic}" onclick="admr_dynamic('anemic','an');"/--%><div id='an'><s:text name="package.label.admregLevel"/>:<%--s:select name="anemicLevel" id="upda_adm_reg_anemic_level" headerKey="none" headerValue="-- Please Select --" list="#{'Mild':'Mild','Moderate':'Moderate','Severe':'Severe'}" labelposition="left" value="%{admreg_view.anemicLevel}"/--%>
                                                                                                                                                                                                                                         <select name="anemicLevel" id="upda_adm_reg_anemic_level">
                                                                                                                                                                                                                                             <s:if test="%{#session.dataList.getAnemicLevel()=='none'}"><option value="none" selected>--<s:text name='global.selectOption.admregPleaSel'/>--</option></s:if>
                                                                                                                                                                                                                                             <s:else><option value="none">--<s:text name='global.selectOption.admregPleaSel'/>--</option></s:else>
                                                                                                                                                                                                                                             <s:if test="%{#session.dataList.getAnemicLevel()==getText('global.selectOption.admregMHMild')}"><option value="<s:text name='global.selectOption.admregMHMild'/>" selected><s:text name="global.selectOption.admregMHMild"/></option></s:if>
                                                                                                                                                                                                                                             <s:else><option value="<s:text name='global.selectOption.admregMHMild'/>"><s:text name="global.selectOption.admregMHMild"/></option></s:else>
                                                                                                                                                                                                                                             <s:if test="%{#session.dataList.getAnemicLevel()==getText('global.selectOption.admregMHMode')}"><option value="<s:text name='global.selectOption.admregMHMode'/>" selected><s:text name="global.selectOption.admregMHMode"/></option></s:if>
                                                                                                                                                                                                                                             <s:else><option value="<s:text name='global.selectOption.admregMHMode'/>"><s:text name="global.selectOption.admregMHMode"/></option></s:else>                                    
                                                                                                                                                                                                                                             <s:if test="%{#session.dataList.getAnemicLevel()==getText('global.selectOption.admregMHSeve')}"><option value="<s:text name='global.selectOption.admregMHSeve'/>" selected><s:text name="global.selectOption.admregMHSeve"/></option></s:if>
                                                                                                                                                                                                                                             <s:else><option value="<s:text name='global.selectOption.admregMHSeve'/>"><s:text name="global.selectOption.admregMHSeve"/></option></s:else>
                                                                                                                                                                                                                                        </select></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregHeart"/>:</td><td><table><tr><td align="right"><s:text name="package.label.admregCHD"/>:</td><td>
                                    <s:if test="%{#session.dataList.getHeartChd()=='Y'}"><input type="radio" name="heartChd" id="upda_adm_reg_heart_chd" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="heartChd" id="upda_adm_reg_heart_chd" value="N"/><s:text name="package.rad.label.no"/></s:if>
                                    <s:else><input type="radio" name="heartChd" id="upda_adm_reg_heart_chd" value="Y"/><s:text name="package.rad.label.yes"/><input type="radio" name="heartChd" id="upda_adm_reg_heart_chd" value="N" checked/><s:text name="package.rad.label.no"/></s:else>
                                    <%--s:radio name="heartChd" id="upda_adm_reg_heart_chd" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.heartChd}" labelposition="right"/--%></td></tr><tr><td align="right"><s:text name="package.label.admregMurmur"/>:</td><td>
                                    <s:if test="%{#session.dataList.getMurmur()=='Y'}"><input type="radio" name="murmur" id="upda_adm_reg_heart_murmur" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="murmur" id="upda_adm_reg_heart_murmur" value="N"/><s:text name="package.rad.label.no"/></s:if>
                                    <s:else><input type="radio" name="murmur" id="upda_adm_reg_heart_murmur" value="Y"/><s:text name="package.rad.label.yes"/><input type="radio" name="murmur" id="upda_adm_reg_heart_murmur" value="N" checked/><s:text name="package.rad.label.no"/></s:else>
                                    <%--s:radio id="upda_adm_reg_heart_murmur" name="murmur" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.murmur}" labelposition="right"/--%></td></tr><tr><td align="right"><s:text name="package.label.admregHeaSound"/>:</td><td>
                                    <s:if test="%{#session.dataList.getHeartSounds()=='Y'}"><input type="radio" name="heartSounds" id="upda_adm_reg_heart_sounds" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="heartSounds" id="upda_adm_reg_heart_sounds" value="N"/><s:text name="package.rad.label.no"/></s:if>
                                    <s:else><input type="radio" name="heartSounds" id="upda_adm_reg_heart_sounds" value="Y"/><s:text name="package.rad.label.yes"/><input type="radio" name="heartSounds" id="upda_adm_reg_heart_sounds" value="N" checked/><s:text name="package.rad.label.no"/></s:else>
                                    <%--s:radio name="heartSounds" id="upda_adm_reg_heart_sounds" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.heartSounds}" labelposition="right"/--%></td></tr></table></td></tr>
                <tr><td align="right"><s:text name="package.label.admregHeadLungs"/>:</td><td><table><tr><td align="right"><s:text name="package.label.admregChestAbnor"/>:</td><td>
                                    <s:if test="%{#session.dataList.getChestAbnormal()=='Y'}"><input type="radio" name="chestAbnormal" id="upda_adm_reg_chest_abnor" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="chestAbnormal" id="upda_adm_reg_chest_abnor" value="N"/><s:text name="package.rad.label.no"/></s:if>
                                    <s:else><input type="radio" name="chestAbnormal" id="upda_adm_reg_chest_abnor" value="Y"/><s:text name="package.rad.label.yes"/><input type="radio" name="chestAbnormal" id="upda_adm_reg_chest_abnor" value="N" checked/><s:text name="package.rad.label.no"/></s:else>
                                    <%--s:radio name="chestAbnormal" id="upda_adm_reg_chest_abnor" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.chestAbnormal}" labelposition="left"/--%></td></tr><tr><td align="right"><s:text name="package.label.admregCerpts"/>:</td><td>
                                    <s:if test="%{#session.dataList.getCrepts()=='Y'}"><input type="radio" name="crepts" id="upda_adm_reg_lungs_crepts" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="crepts" id="upda_adm_reg_lungs_crepts" value="N"/><s:text name="package.rad.label.no"/></s:if>
                                    <s:else><input type="radio" name="crepts" id="upda_adm_reg_lungs_crepts" value="Y"/><s:text name="package.rad.label.yes"/><input type="radio" name="crepts" id="upda_adm_reg_lungs_crepts" value="N" checked/><s:text name="package.rad.label.no"/></s:else>
                                    <%--s:radio name="crepts" id="upda_adm_reg_lungs_crepts" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.crepts}" labelposition="left"/--%></td></tr><tr><td align="right"><s:text name="package.label.admregBAE"/>:</td><td>
                                    <s:if test="%{#session.dataList.getLungsBea()=='Y'}"><input type="radio" name="lungsBea" id="upda_adm_reg_lungs_bae" value="Y" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="lungsBea" id="upda_adm_reg_lungs_bae" value="N"/><s:text name="package.rad.label.no"/></s:if>
                                    <s:else><input type="radio" name="lungsBea" id="upda_adm_reg_lungs_bae" value="Y"/><s:text name="package.rad.label.yes"/><input type="radio" name="lungsBea" id="upda_adm_reg_lungs_bae" value="N" checked/><s:text name="package.rad.label.no"/></s:else>
                                    <%--s:radio name="lungsBea" id="upda_adm_reg_lungs_bae" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.lungsBea}" labelposition="left"/--%></td></tr></table></td></tr>
                <tr><td align="right"><s:text name="package.label.admregPerAbdomen"/>:</td><td>
                        <s:if test="%{#session.dataList.getParabdomenOrg()=='Y'}"><input type="radio" name="parabdomenOrg" id="upda_adm_reg_parabdomen" value="Y" onclick="admr_dynamic('parabdomenOrg','pb');" checked/><s:text name="package.rad.label.yes"/><input type="radio" name="parabdomenOrg" id="upda_adm_reg_parabdomen" value="N" onclick="admr_dynamic('parabdomenOrg','pb');"/><s:text name="package.rad.label.no"/></s:if>
                        <s:else><input type="radio" name="parabdomenOrg" id="upda_adm_reg_parabdomen" value="Y" onclick="admr_dynamic('parabdomenOrg','pb');"/><s:text name="package.rad.label.yes"/><input type="radio" name="parabdomenOrg" id="upda_adm_reg_parabdomen" value="N" onclick="admr_dynamic('parabdomenOrg','pb');" checked/><s:text name="package.rad.label.no"/></s:else>
                        <%--s:radio name="parabdomenOrg" id="upda_adm_reg_parabdomen" list="#{'Y':'Yes','N':'No'}" value="%{admreg_view.parabdomenOrg}" onclick="admr_dynamic('parabdomenOrg','pb');"/--%><div id='pb'><s:text name="package.label.admregSpecify"/>:<%--s:select name="specifyParabdomen" id="upda_adm_reg_parabdomen_specify" headerKey="none" headerValue="-- Please Select --" list="#{'spleenomegaly':'Spleenomegaly','heptomegaly':'Heptomegaly'}" labelposition="left" value="%{admreg_view.specifyParabdomen}"/--%>
                                                                                                                                                                                                                                                                    <select name="specifyParabdomen" id="upda_adm_reg_parabdomen_specify">
                                                                                                                                                                                                                                                                        <s:if test="%{#session.dataList.getSpecifyParabdomen()=='none'}"><option value="none" selected>--<s:text name='global.selectOption.admregPleaSel'/>--</option></s:if>
                                                                                                                                                                                                                                                                        <s:else><option value="none">--<s:text name='global.selectOption.admregPleaSel'/>--</option></s:else>
                                                                                                                                                                                                                                                                        <s:if test="%{#session.dataList.getSpecifyParabdomen()==getText('global.selectOption.admregParaSpleen')}"><option value="<s:text name='global.selectOption.admregParaSpleen'/>" selected><s:text name="global.selectOption.admregParaSpleen"/></option></s:if>
                                                                                                                                                                                                                                                                        <s:else><option value="<s:text name='global.selectOption.admregParaSpleen'/>"><s:text name="global.selectOption.admregParaSpleen"/></option></s:else>
                                                                                                                                                                                                                                                                        <s:if test="%{#session.dataList.getSpecifyParabdomen()==getText('global.selectOption.admregParaHepto')}"><option value="<s:text name='global.selectOption.admregParaHepto'/>" selected><s:text name="global.selectOption.admregParaHepto"/></option></s:if>
                                                                                                                                                                                                                                                                        <s:else><option value="<s:text name='global.selectOption.admregParaHepto'/>"><s:text name="global.selectOption.admregParaHepto"/></option></s:else>
                                                                                                                                                                                                                                                                   </select></div></td></tr>
                <tr><td align="right"><s:text name="package.label.admregSkinDisea"/>:</td><td><%--s:textfield name="skinDiseases" id="upda_adm_reg_skin_diseases" value="%{admreg_view.skinDiseases}" cssClass=<select"keyboardInput"/--%> <input type="text" name="skinDiseases" id="upda_adm_reg_skin_diseases" value="<%=adm.getSkinDiseases()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></td></tr>
                <tr><td colspan="2" align="center"><b><s:text name="package.label.admregProvDiag"/></b></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCNS"/>:</td><td><%--s:textfield name="cnsDiag" id="upda_adm_reg_cns" value="%{admreg_view.cnsDiag}" cssClass="keyboardInput"/--%><input type="text" name="cnsDiag" id="upda_adm_reg_cns" value="<%=adm.getCnsDiag()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCVS"/>:</td><td><%--s:textfield name="cvsDiag" id="upda_adm_reg_cvs" value="%{admreg_view.cvsDiag}" cssClass="keyboardInput"/--%><input type="text" name="cvsDiag" id="upda_adm_reg_cvs" value="<%=adm.getCvsDiag()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></td></tr>
                <tr><td align="right"><s:text name="package.label.admregLabelLungs"/>:</td><td><%--s:textfield name="lungsDiag" id="upda_adm_reg_lungs" value="%{admreg_view.lungsDiag}" cssClass="keyboardInput"/--%><input type="text" name="lungsDiag" id="upda_adm_reg_lungs" value="<%=adm.getLungsDiag()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></td></tr>
                <tr><td align="right"><s:text name="package.label.admregGIT"/>:</td><td><%--s:textfield name="gitDiag" id="upda_adm_reg_git" value="%{admreg_view.gitDiag}" cssClass="keyboardInput"/--%><input type="text" name="gitDiag" id="upda_adm_reg_git" value="<%=adm.getGitDiag()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></td></tr>
                <tr><td align="right"><s:text name="package.label.admregKidney"/>:</td><td><%--s:textfield name="kidneyDiag" id="upda_adm_reg_kidney" value="%{admreg_view.kidneyDiag}" cssClass="keyboardInput"/--%><input type="text" name="kidneyDiag" id="upda_adm_reg_kidney" value="<%=adm.getKidneyDiag()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></td></tr>
                <tr><td align="right"><s:text name="package.label.admregSkeSys"/>:</td><td><%--s:textfield name="skeletalSysDiag" id="upda_adm_reg_ske_sys" value="%{admreg_view.skeletalSysDiag}" cssClass="keyboardInput"/--%><input type="text" name="skeletalSysDiag" id="upda_adm_reg_ske_sys" value="<%=adm.getSkeletalSysDiag()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></td></tr>
                <tr><td align="right"><s:text name="package.label.admregOthSpec"/>:</td><td><%--s:textfield name="otherDiag" id="upda_adm_reg_prodia_others" value="%{admreg_view.otherDiag}" cssClass="keyboardInput"/--%><input type="text" name="otherDiag" id="upda_adm_reg_prodia_others" value="<%=adm.getOtherDiag()%>" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'></input></td></tr>
                <tr><td align="right"><s:text name="package.label.admregOffiSuggest"/>:</td><td><%--s:textarea name="treatment" id="upda_adm_reg_doctors_sugg" cols="20" rows="4" value="%{admreg_view.treatment}" cssClass="keyboardInput"/--%><textarea name="treatment" id="upda_adm_reg_doctors_sugg" cols="20" rows="4" onfocus='VirtualKeyboard.attachInput(this);currentTB=this.id;'><%=adm.getTreatment()%></textarea></td></tr>
                <tr><td colspan="2" align="center"><input type="submit" value="<s:text name="global.button.medAdmRegModify"/>" align="center"/></td></tr>
            </s:form>
         </table>
        </center>
        <div id="dialog-form_update_adm_reg_fem" title="<s:text name="global.heading.admRegister"/> <s:text name="global.heading.preview"/>">
	<form name="adm_reg_dialog">
	<table border="1">
                <tr><td align="right"><s:text name='package.label.rrProfId'/>:</td><td><span id="upda_adm_reg_profile_id_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregWeiAtAdm"/>:</td><td><span id="upda_adm_reg_adm_weight_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregHeiAtAdm"/>:</td><td><span id="upda_adm_reg_adm_height_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCongiAno"/>:</td><td><span id="upda_adm_reg_conano_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregNameSpec"/>:</td><td><span id="upda_adm_reg_conano_specify_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregPhyHandi"/>:</td><td><span id="upda_adm_reg_phyhan_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregDisabSpec"/>:</td><td><span id="upda_adm_reg_phyhan_specify_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregMenHandi"/>:</td><td><span id="upda_adm_reg_menhan_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregStatSpec"/>:</td><td><span id="upda_adm_reg_menhan_specify_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFits"/>:</td><td><span id="upda_adm_reg_fits_case_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregTreatSpec"/>:</td><td><span id="upda_adm_reg_fitstreat_specify_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCommuHist"/>:</td><td><span id="upda_adm_reg_commd_hist_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregDiseaSpec"/>:</td><td><span id="upda_adm_reg_commd_specify_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregSpecOth"/>:</td><td><span id="upda_adm_reg_commd_others_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregBodyPain"/>:</td><td><span id="upda_adm_reg_body_pains_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFever"/>:</td><td><span id="upda_adm_reg_fever_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregVomit"/>:</td><td><span id="upda_adm_reg_vomiting_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregOthSpec"/>:</td><td><span id="upda_adm_reg_gencomp_others_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregPrevHealHist"/>:</td><td><span id="upda_adm_reg_prev_hist_span"></span></td></tr>
                <!--for Female gender-->
                <tr><td align="right"><s:text name="package.label.admregFemMarStat"/>:</td><td><span id="upda_adm_reg_mar_stat_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemMenarAttai"/>:</td><td><span id="upda_adm_reg_att_menar_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemAtAge"/>:</td><td><span id="upda_adm_reg_memar_age_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemLMP"/>:</td><td><span id="upda_adm_reg_lmp_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemAbuse"/>:</td><td><span id="upda_adm_reg_seabuse_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemExtFin"/>:</td><td><span id="upda_adm_reg_exter_fin_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregFemLocExam"/>:</td><td><span id="upda_adm_reg_loc_fin_span"></span></td></tr>
                <!--for Female gender-->
                <tr><td align="right"><s:text name="package.label.admregPhyAppear"/>:</td><td><span id="upda_adm_reg_phyapp_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregConscLevel"/>:</td><td><span id="upda_adm_reg_drug_addiction_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregDrugSpec"/>:</td><td><span id="upda_adm_reg_drug_specify_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregAnemic"/>:</td><td><span id="upda_adm_reg_anemic_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregLevel"/>:</td><td><span id="upda_adm_reg_anemic_level_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregHeart"/> <s:text name="package.label.admregCHD"/>:</td><td><span id="upda_adm_reg_heart_chd_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregHeart"/> <s:text name="package.label.admregMurmur"/>:</td><td><span id="upda_adm_reg_heart_murmur_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregHeaSound"/>:</td><td><span id="upda_adm_reg_heart_sounds_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregChestAbnor"/>:</td><td><span id="upda_adm_reg_chest_abnor_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCerpts"/>:</td><td><span id="upda_adm_reg_lungs_crepts_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregBAE"/>:</td><td><span id="upda_adm_reg_lungs_bae_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregPerAbdomen"/>:</td><td><span id="upda_adm_reg_parabdomen_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregSpecify"/>:</td><td><span id="upda_adm_reg_parabdomen_specify_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregSkinDisea"/>:</td><td><span id="upda_adm_reg_skin_diseases_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCNS"/>:</td><td><span id="upda_adm_reg_cns_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregCVS"/>:</td><td><span id="upda_adm_reg_cvs_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregLabelLungs"/>:</td><td><span id="upda_adm_reg_lungs_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregGIT"/>:</td><td><span id="upda_adm_reg_git_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregKidney"/>:</td><td><span id="upda_adm_reg_kidney_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregSkeSys"/>:</td><td><span id="upda_adm_reg_ske_sys_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregOthSpec"/>:</td><td><span id="upda_adm_reg_prodia_others_span"></span></td></tr>
                <tr><td align="right"><s:text name="package.label.admregOffiSuggest"/>:</td><td><span id="upda_adm_reg_doctors_sugg_span"></span></td></tr>
        </table>
	</form>
        </div>


</s:if>
<s:else>
    <h2><s:text name="global.errmsg.DocMajErrConAdmin"/></h2>
</s:else>
    </body>
</html>
