<%@taglib  prefix="s" uri="/struts-tags" %>

<OPTION value="-1">-----<s:text name="global.option.headerKey"/>----</OPTION>
<OPTION value="<s:text name="global.country.india"/>"><s:text name="global.country.india"/></OPTION>
<!--OPTION value="Argentina">Argentina</OPTION>
<OPTION value="Australia">Australia</OPTION>
<OPTION value="Austria">Austria</OPTION>
<OPTION value="Barbados">Barbados</OPTION>
<OPTION value="Belgium">Belgium</OPTION>
<OPTION value="Bermuda">Bermuda</OPTION>
<OPTION value="Brazil">Brazil</OPTION>
<OPTION value="Canada">Canada</OPTION>
<OPTION value="Chile">Chile</OPTION>
<OPTION value="China">China</OPTION>
<OPTION value="Colombia">Colombia</OPTION>
<OPTION value="Croatia">Croatia</OPTION>
<OPTION value="Cyprus">Cyprus</OPTION>
<OPTION value="Czech Repulic">Czech Repulic</OPTION>
<OPTION value="Denmark">Denmark</OPTION>
<OPTION value="Dominican Republic">Dominican Republic</OPTION>
<OPTION value="Finland">Finland</OPTION>
<OPTION value="France">France</OPTION>
<OPTION value="Germany">Germany</OPTION>
<OPTION value="Greece">Greece</OPTION>
<OPTION value="Hong Kong">Hong Kong</OPTION>
<OPTION value="Hungary">Hungary</OPTION>
<OPTION value="Iceland">Iceland</OPTION>
<OPTION value="India">India</OPTION>
<OPTION value="Indonesia">Indonesia</OPTION>
<OPTION value="Ireland">Ireland</OPTION>
<OPTION value="Israel">Israel</OPTION>
<OPTION value="Italy">Italy</OPTION>
<OPTION value="Japan">Japan</OPTION>
<OPTION value="Malaysia">Malaysia</OPTION>
<OPTION value="Malta">Malta</OPTION>
<OPTION value="Mexico">Mexico</OPTION>
<OPTION value="Netherlands">Netherlands</OPTION>
<OPTION value="New Zealand">New Zealand</OPTION>
<OPTION value="Norway">Norway</OPTION>
<OPTION value="Pakistan">Pakistan</OPTION>
<OPTION value="Peru">Peru</OPTION>
<OPTION value="Philippines">Philippines</OPTION>
<OPTION value="Poland">Poland</OPTION>
<OPTION value="Portugal">Portugal</OPTION>
<OPTION value="Russia">Russia</OPTION>
<OPTION value="Saudi Arabia">Saudi Arabia</OPTION>
<OPTION value="Singapore">Singapore</OPTION>
<OPTION value="Slovenia">Slovenia</OPTION>
<OPTION value="South Africa">South Africa</OPTION>
<OPTION value="South Korea">South Korea</OPTION>
<OPTION value="Spain">Spain</OPTION>
<OPTION value="Sweden">Sweden</OPTION>
<OPTION value="Switzerland">Switzerland</OPTION>
<OPTION value="Taiwan">Taiwan</OPTION>
<OPTION value="Thailand">Thailand</OPTION>
<OPTION value="Turkey">Turkey</OPTION>
<OPTION value="United Arab Emirates">UAE</OPTION>
<OPTION value="United Kingdom">United Kingdom</OPTION>
<OPTION value="USA">United States</OPTION>
<OPTION value="Venezuela">Venezuela</OPTION>
<OPTION value="Other">Other</OPTION-->
